# Generated by Django 3.2.7 on 2021-10-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_productinbasket_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='product_id',
            field=models.IntegerField(default=None),
        ),
    ]
