# Generated by Django 3.2.7 on 2021-10-31 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_productinbasket_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='product_id',
        ),
    ]
