# Generated by Django 3.2.7 on 2021-10-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_productinbasket_nmb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='nmb',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
