# Generated by Django 3.2.7 on 2021-11-07 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharactDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc1', models.CharField(db_index=True, default=None, max_length=200, null=True)),
                ('desc2', models.CharField(db_index=True, default=None, max_length=200, null=True)),
                ('desc3', models.CharField(db_index=True, default=None, max_length=200, null=True)),
                ('desc4', models.CharField(db_index=True, default=None, max_length=200, null=True)),
                ('desc5', models.CharField(db_index=True, default=None, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.category'),
        ),
        migrations.CreateModel(
            name='CharactName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(db_index=True, default=None, max_length=200, null=True)),
                ('name2', models.CharField(db_index=True, default=None, max_length=200, null=True)),
                ('name3', models.CharField(db_index=True, default=None, max_length=200, null=True)),
                ('name4', models.CharField(db_index=True, default=None, max_length=200, null=True)),
                ('name5', models.CharField(db_index=True, default=None, max_length=200, null=True)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characts', to='app.category')),
                ('charact_desc_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characts_name', to='app.charactdesc')),
            ],
        ),
        migrations.AddField(
            model_name='charactdesc',
            name='charact_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characts_desc', to='app.charactname'),
        ),
        migrations.AddField(
            model_name='charactdesc',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characts_desc', to='app.product'),
        ),
    ]
