# Generated by Django 3.2.7 on 2021-11-07 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_charactdesc_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactname',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characts_name', to='app.product'),
        ),
    ]
