# Generated by Django 3.2.7 on 2021-11-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_avatars/default.jpg', null=True, upload_to='profile_avatars/%Y/%m/%d', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='', max_length=64, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Телефон'),
        ),
    ]
