# Generated by Django 3.2.7 on 2021-11-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20211109_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_avatars/default.jpg', upload_to='profile_avatars/%Y/%m/%d', verbose_name='Аватар'),
        ),
    ]
