# Generated by Django 3.2.7 on 2021-11-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_charactdesc_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactdesc',
            name='product_id',
        ),
    ]
